matchBlocks=minecraft:mud_brick_slab:type=bottom
faces:top
method=ctm_compact
tiles=minecraft:block/mud_bricks_bottom_outer <default> minecraft:block/mud_bricks_bottom_vertical minecraft:block/mud_bricks_bottom_horizontal bottom_4
connect=block