matchBlocks=minecraft:mud_bricks minecraft:mud_brick_slab:type=bottom minecraft:mud_brick_stairs:half=bottom
faces:bottom
method=ctm_compact
tiles=minecraft:block/mud_bricks_bottom_outer minecraft:block/mud_bricks_top bottom_2 bottom_3 bottom_4
connect=tile