matchBlocks=minecraft:resin_bricks minecraft:resin_brick_slab minecraft:resin_brick_stairs:half=bottom
faces=bottom

method=ctm_compact
tiles=bottom_0 <default> bottom_2 bottom_3 bottom_4 bottom_tile_0
ctm.0=5

connect=tile