matchBlocks=minecraft:brick_slab:type=double minecraft:brick_slab:type=top
faces=bottom

method=ctm_compact

tiles=slab_top_0 <default> slab_top_2 slab_top_3 slab_top_4
ctm.0=1
ctm.1=3
ctm.3=3
ctm.12=2
ctm.36=2

connect=block

innerSeams=false